FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

RUN dotnet tool install --global NetSparkleUpdater.Tools.AppCastGenerator
ENV PATH="$PATH:/root/.dotnet/tools"

VOLUME ["/keys"]

ENTRYPOINT ["netsparkle-generate-appcast", "--generate-keys", "--key-path", "/keys"]