# escape=`

FROM mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2022 AS build
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . .
RUN dotnet publish Finance_Manager_WPF_Front.csproj `
    --self-contained true `
    --runtime win-x64 `
    --configuration Release `
    --output /publish `
    /p:PublishSingleFile=true `
    /p:PublishTrimmed=false

FROM mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2022 AS generate
WORKDIR /app

COPY --from=build /publish /app/publish

RUN dotnet tool install --global NetSparkleUpdater.Tools.AppCastGenerator
ENV PATH="$PATH:C:/Users/ContainerAdministrator/.dotnet/tools"

VOLUME ["C:/out", "C:/keys", "C:/publish"]

ENV APP_VERSION=0.0.0

# powershell -Command 
ENTRYPOINT "netsparkle-generate-appcast `
    --appcast-output-directory C:/out `
    --binaries C:/app/publish `
    --ext exe `
    --os windows-x64 `
    --product-name FinanceManagerWPF `
    --file-version $env:APP_VERSION `
    --key-path C:/keys `
    --human-readable true `
    --output-file-name appcast"
