name: Build and generate exe and appcast

on:
  push:
    tags:
      - "v*"

jobs:
  prepare-files:
    runs-on: [self-hosted, updater]
    steps:
      - name: Copy .env and keys to temp dir
        run: |
          mkdir -p /tmp/env-keys
          cp /home/plotnoplodviktor/enviroment_files/finman_wpf_enviroment/.env /tmp/env-keys/env
          cp -r /home/plotnoplodviktor/finman_wpf/updates/keys /tmp/env-keys/keys

      - name: Upload .env and keys as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-and-keys
          path: /tmp/env-keys

  build-windows:
    needs: prepare-files
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download env and keys artifact
        uses: actions/download-artifact@v4
        with:
          name: env-and-keys
          path: C:\temp\env-keys

      - name: Get version from tag
        shell: pwsh
        run: |
          $tag = $env:GITHUB_REF_NAME
          $ver = $tag -replace '^v', ''
          "APP_VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Build Docker image
        run: |
          docker build `
          --build-arg APP_VERSION=$env:APP_VERSION `
          -t appcast-generator-win ./Finance_Manager_WPF_Front

      - name: Create publish and out folders
        run: |
          mkdir C:\temp\publish
          mkdir C:\temp\out

      - name: Export app archive from image
        run: |
          docker create --name export-container appcast-generator-win
          docker cp export-container:C:\app\FinanceManagerWPF.zip C:\temp\publish
          docker rm export-container

      - name: Run appcast-generator container
        shell: pwsh
        run: |
          docker run --rm `
            -v C:\temp\env-keys\keys:C:\Users\ContainerAdministrator\AppData\Local\netsparkle `
            -v C:\temp\out:C:\out `
            --env-file C:\temp\env-keys\env `
            appcast-generator-win

      - name: Upload out folder
        uses: actions/upload-artifact@v4
        with:
          name: out-folder
          path: C:\temp\out

      - name: Upload publish folder
        uses: actions/upload-artifact@v4
        with:
          name: publish-folder
          path: C:\temp\publish

  save-artifacts-on-server:
    needs: build-windows
    runs-on: [self-hosted, updater]
    steps:
      - name: Download out
        uses: actions/download-artifact@v4
        with:
          name: out-folder
          path: /home/plotnoplodviktor/finman_wpf/updates/out

      - name: Download publish
        uses: actions/download-artifact@v4
        with:
          name: publish-folder
          path: /home/plotnoplodviktor/finman_wpf/updates/publish

      - name: Cleanup temp folder
        run: rm -rf /tmp/env-keys
