name: Build and generate exe

on:
  push:
    tags:
      - "v*"

jobs:
  prepare-files:
    runs-on: [self-hosted, finman_wpf]
    steps:
      - name: Copy config to temp dir
        run: |
          mkdir -p /tmp/config
          cp /home/ubuntu/configs/finman_wpf_config/appsettings.json /tmp/config

      - name: Upload config as artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: /tmp/config

  build-binary:
    needs: prepare-files
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download config artifact
        uses: actions/download-artifact@v4
        with:
          name: config
          path: C:\temp\config

      - name: Get version from tag
        shell: pwsh
        run: |
          $tag = $env:GITHUB_REF_NAME
          $ver = $tag -replace '^v', ''
          "APP_VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Move appsettings to repo
        shell: pwsh
        run: Move-Item -Path "C:\temp\config\appsettings.json" -Destination ".\Finance_Manager_WPF_Front" -Force

      - name: Build Docker image
        run: |
          docker build `
          --build-arg APP_VERSION=$env:APP_VERSION `
            -t finman-wpf:latest `
            ./Finance_Manager_WPF_Front

      - name: Create publish folder
        run: |
          mkdir C:\temp\publish

      - name: Export app archive from image
        run: |
          docker create --name export-container finman-wpf:latest
          docker cp export-container:C:\app\FinanceManagerWPF.zip C:\temp\publish
          docker rm export-container

      - name: Upload publish folder
        uses: actions/upload-artifact@v4
        with:
          name: publish-folder
          path: C:\temp\publish

  save-artifacts-on-server:
    needs: build-binary
    runs-on: [self-hosted, finman_wpf]
    steps:
      - name: Download publish
        uses: actions/download-artifact@v4
        with:
          name: publish-folder
          path: /home/ubuntu/projects/finman_wpf/updates/publish

      - name: Cleanup temp folder
        run: rm -rf /tmp/config
