name: Build and generate exe and appcast

on:
  push:
    tags:
      - "v*"

jobs:
  prepare-files:
    runs-on: [self-hosted, updater]
    steps:
      - name: Copy configs and keys to temp dir
        run: |
          mkdir -p /tmp/configs-keys/configs
          mkdir -p /tmp/configs-keys/keys
          cp -r /home/plotnoplodviktor/configs/finman_wpf_config/. /tmp/configs-keys/configs
          cp -r /home/plotnoplodviktor/finman_wpf/updates/keys/* /tmp/configs-keys/keys

      - name: Debug configs contents
        run: |
          echo "Configs dir contains:"
          ls -la /tmp/configs-keys/configs

      - name: Upload configs and keys as artifact
        uses: actions/upload-artifact@v4
        with:
          name: configs-and-keys
          path: /tmp/configs-keys

  build-binary-and-appcast:
    needs: prepare-files
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download configs and keys artifact
        uses: actions/download-artifact@v4
        with:
          name: configs-and-keys
          path: C:\temp\configs-keys

      - name: Get version from tag
        shell: pwsh
        run: |
          $tag = $env:GITHUB_REF_NAME
          $ver = $tag -replace '^v', ''
          "APP_VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Encrypt appsettings.json
        run: |
          openssl enc -aes-256-cbc -pbkdf2 `
            -in C:\temp\configs-keys\configs\appsettings.json `
            -out .\Finance_Manager_WPF_Front\appsettings.enc `
            -pass pass:"${{ secrets.ENCRYPT_APPSETTINGS_PASSWORD }}"
        shell: pwsh

      - name: Build Docker image
        run: |
          docker build `
          --build-arg APP_VERSION=$env:APP_VERSION `
          --build-arg APPSETTINGS_PASSWORD="${{ secrets.ENCRYPT_APPSETTINGS_PASSWORD }}" `
          -t appcast-generator-win ./Finance_Manager_WPF_Front

      - name: Create publish and out folders
        run: |
          mkdir C:\temp\publish
          mkdir C:\temp\out

      - name: Export app archive from image
        run: |
          docker create --name export-container appcast-generator-win
          docker cp export-container:C:\app\FinanceManagerWPF.zip C:\temp\publish
          docker rm export-container

      - name: Run appcast-generator container
        shell: pwsh
        run: |
          docker run --rm `
            -v C:\temp\configs-keys\keys:C:\Users\ContainerAdministrator\AppData\Local\netsparkle `
            -v C:\temp\out:C:\out `
            --env-file C:\temp\configs-keys\configs\.env `
            appcast-generator-win

      - name: Upload out folder
        uses: actions/upload-artifact@v4
        with:
          name: out-folder
          path: C:\temp\out

      - name: Upload publish folder
        uses: actions/upload-artifact@v4
        with:
          name: publish-folder
          path: C:\temp\publish

  save-artifacts-on-server:
    needs: build-binary-and-appcast
    runs-on: [self-hosted, updater]
    steps:
      - name: Download out
        uses: actions/download-artifact@v4
        with:
          name: out-folder
          path: /home/plotnoplodviktor/finman_wpf/updates/out

      - name: Download publish
        uses: actions/download-artifact@v4
        with:
          name: publish-folder
          path: /home/plotnoplodviktor/finman_wpf/updates/publish

      - name: Cleanup temp folder
        run: rm -rf /tmp/configs-keys
