name: Build appcast update files

on:
  push:
    tags:
      - "v*"

jobs:
  generate-appcast:
    runs-on: [self-hosted, updater]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version from tag
        run: echo "APP_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build appcast-generator Docker image
        run: docker build -t appcast-generator ./Finance_Manager_WPF_Front

      - name: Run appcast-generator
        run: |
          docker run --rm \
            -v /home/plotnoplodviktor/finman_wpf/updates:/out \
            -v /home/plotnoplodviktor/finman_wpf/updates/keys:/keys \
            -v /home/plotnoplodviktor/finman_wpf/updates/publish:/app/publish \
            --env-file /home/plotnoplodviktor/enviroment_files/finman_wpf_enviroment/.env \
            -e APP_VERSION=${{ env.APP_VERSION }} \
            appcast-generator
